//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVaccineSystem.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppoimentMaster
    {
        public int Id { get; set; }
        public Nullable<int> SlotID { get; set; }
        public Nullable<int> CenterId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VaccineId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> AppoimentDate { get; set; }
    
        public virtual CenterSlot CenterSlot { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual Vaccine Vaccine { get; set; }
        public virtual VaccineCenter VaccineCenter { get; set; }
    }
}
